app = 'ekaty-db-agent'
primary_region = 'dfw'

[build]

[env]
  APP_ENV = 'production'
  TIMEZONE = 'America/Chicago'
  DB_TYPE = 'sqlite'
  DB_PATH = '/data/ekaty.db'
  LOG_LEVEL = 'INFO'
  LOCATION_LAT = '29.7858'
  LOCATION_LNG = '-95.8245'
  SEARCH_RADIUS = '15000'

[mounts]
  source = 'ekaty_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
